server:
  port: 8090

spring:
#  main:
#    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://192.168.1.109:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:/config/mcp-servers-config-4.json
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-Hvvp1HH0fYQoUmfw0b865464Ea3c4d3b82Ff7b128e260aFf
      chat:
        options:
          model: gpt-4o
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://58a39caa684c41bf9bed-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

logging:
  level:
    root: info
  config: classpath:logback-spring.xml